### PR TITLE
Defer module.derive’s copy to a microtask.

### LINKED ISSUE #178: module.derive (import-with) doesn’t handle circular imports.
*module*.derive creates a copy of the module:

https://github.com/observablehq/runtime/blob/0801ad4a4a975e7e79e1c0143956a0b8a0bc3232/src/module.js#L61-L88

The problem is if you have circular imports, *runtime*.module will give you an empty module:

https://github.com/observablehq/runtime/blob/0801ad4a4a975e7e79e1c0143956a0b8a0bc3232/src/runtime.js#L53-L72

So, we need *module*.derive to somehow be lazy, rather than copying the variables greedily into the new module.

### PR DESCRIPTION
**Pull request by mbostock**
Fixes #178.

### CODE REVIEW

**Comment by jashkenas** [comment]
Neat stab at a fix -- (I especially appreciate the problem diagram in #178). But the failing tests make it look as though this change is causing generator ticks to skip over yielded values somehow ... even without any imports being involved.

**Comment by mbostock** [comment]
The failing tests are caused by differences between Node 10 and Node 12, which I fixed in d2fa75d2d82ac41a66762dd00f4b259929a6f960. I’ll see if I can update the CI config…

**Comment by mbostock** [comment]
Okay, I’ve got the tests working on master again in Node 10 in be9bd9a540b4d602087215e9c085fee7c97101e6. I don’t fully understand the timing…

**Comment by jashkenas** [comment]
Ah good.

In that case, this looks great. It's nice that just making the import construction incremental and deferred fixes this circularity issue.

**Comment by mbostock** [comment]
Awesome, thanks. Yeah, my take is that *module*.derive has to make a copy, because it needs to rewire the graph with whatever you inject. So we just need to wait until the right moment to make that copy. Putting it in a microtask is a little arbitrary—it might be safer to, say, do it in the immediately prior to runtime._computing resolving. But this seems fine?

**Comment by jashkenas** [comment]
Yes, I agree. I think that the equivalent alternative here would be to wrap up the continuation of `module.derive` into a callback that is registered with the `runtime`, and then just before the runtime attempts its next tick, you'd finish the derivations. But as long as microtasks go first, this should be the same?

**Comment by mbostock** [comment]
Yep!

**Pull request merged**
